package com.jh.emp.util;

public interface DBQuery {
	
	public static final String CREATE_EMP_TABLE="CREATE TABLE EMPLOY_INFO (EMPID INT (10),EMPNAME VARCHAR (20),EMAIL VARCHAR(50),DEPARTMENT VARCHAR(30),PASSWORD VARCHAR(20),LOCATION VARCHAR(30))";
	public static final String INSERT_EMP_INFO="INSERT INTO EMPLOY_INFO(EMPID,EMPNAME,EMAIL,DEPARTMENT,PASSWORD,LOCATION)VALUES(?,?,?,?,?,?) ";
	public static final String GET_LOGIN_INFO ="SELECT * FROM EMPLOY_INFO WHERE EMAIL=? AND PASSWORD=?";
	public static final String UPDATE_EMP_INFO_LOCATION_BY_ENPID="UPDATE EMPLOY_INFO SET LOCATION =? WHERE EMPID =?";
	public static final String READ_EMP_INFO_BY_EMPID ="SELECT * FROM EMPLOY_INFO WHERE EMPID=?";
	
	public static final String READ_ALL_EMP_INFO ="SELECT * FROM EMPLOY_INFO";
	
   
}
